profile: default
region: ap-northeast-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: lambda_adminkun_bot
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: adminkun.lambda_handler
  description: lambda function for adminkun twitter bot
  timeout: 30
  memory_size: 128
